SCR_MissionHeader {
 World "{AFF7E8CE6B1AFE74}Worlds/GameMaster.ent"
 m_sName "UK1 United Kingdom"
 m_sAuthor "Yoga-Flame Muzza MinDBlanK"
 m_sDescription "UK1 United Kingdom map"
 m_sDetails "An exclusive map for Gurkhaz server"
 m_sIcon "{49B729E0576C1D1C}Images/United Kingdom - Game Master.edds"
 m_sLoadingScreen "{49B729E0576C1D1C}Images/United Kingdom - Game Master.edds"
 m_sPreviewImage "{49B729E0576C1D1C}Images/United Kingdom - Game Master.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}