SCR_MissionHeader {
 World "{AFF7E8CE6B1AFE74}Worlds/GameMaster.ent"
 m_sName "United Kingdom - Game Master"
 m_sAuthor "Yoga-Flame, MindBlank, Muzza"
 m_sDescription "<Insert world description>"
 m_sIcon "{49B729E0576C1D1C}Images/gurk-banner-discord.edds"
 m_sLoadingScreen "{49B729E0576C1D1C}Images/gurk-banner-discord.edds"
 m_sPreviewImage "{49B729E0576C1D1C}Images/gurk-banner-discord.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bIsSavingEnabled 1
 m_sSaveFileName "UK1 Gurkhaz United Kingdom"
 m_fDayTimeAcceleration 4
 m_fNightTimeAcceleration 12
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
}